version: '3'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
    ports:
      - 5432:5432
    networks:
      - private
  
  zabbix-server:
    restart: unless-stopped
    links:
      - postgres:postgres
    image: zabbix/zabbix-server-pgsql:alpine-6.2-latest
    environment:
      DB_SERVER_HOST: postgres
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
    ports:
      - 10051:10051
    depends_on:
      - postgres
    networks:
      - private

  zabbix-frontend:
    restart: unless-stopped
    links:
      - zabbix-server:zabbix-server
      - postgres:postgres
    image: zabbix/zabbix-web-nginx-pgsql:alpine-6.2-latest
    environment:
      DB_SERVER_HOST: postgres
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      ZBX_SERVER_HOST: zabbix-server
    ports:
      - 80:8080
      - 443:8443
    volumes:
      - /etc/ssl/nginx:/etc/ssl/nginx:ro
    depends_on:
      - postgres
      - zabbix-server
    networks:
      - private

  grafana:
    image: grafana/grafana-oss:latest
    user: root
    ports:
      - 3000:3000
    networks:
      - private

networks:
  private:
    driver: bridge